
import * as fs from 'fs'
import * as globpackg from 'glob'
import * as Handlebars from "handlebars"
import * as path from "path"
import {getLayoutData} from "./getLayoutData"
import {getExampleData} from "./getExampleData"
import {generateSVGs} from "./generateSVG"

const glob = globpackg.glob

const DOCS_TEMPLATE_DIR = './templates'
const EXAMPLES_DIR = '../examples'

const DOCS_OUTPUT_DIR = '../docs'
const SVG_OUTPUT_DIR = '../docs/generated/layouts'

function ensuredir(dir: string){
  var fulldir = path.resolve(__dirname, dir)
  if (!fs.existsSync(fulldir)){
    fs.mkdirSync(fulldir);
  }
}

fs.rmdirSync('../docs/generated', { recursive: true })
ensuredir('../docs')
ensuredir('../docs/generated')
ensuredir('../docs/generated/layouts')


var layouts = getLayoutData()
var examples = getExampleData(EXAMPLES_DIR)

var allData = {
  layouts,
  examples
}
//SVGs
generateSVGs(allData.layouts, SVG_OUTPUT_DIR)

//Docs
glob(path.resolve(__dirname, DOCS_TEMPLATE_DIR) + '/**/*.handlebars.md',  function (err: any, res: any) {
  if (err) {
    console.log('Error', err);
  } else {
    var templates = <string[]> res
    for(var template of templates.sort()){
      const templateStr = fs.readFileSync(template).toString('utf8')
      const templateFn = Handlebars.compile(templateStr, { noEscape: true })
      const result = `<!---
This file was automatically generated by a docs-generator scripts.
Do not edit this file directly.
It used the template: "${template}"
-->

` + templateFn(allData)

      fs.writeFileSync(path.resolve(template.replace('docs-generators/templates','').replace('.handlebars','')), result, 'utf8')
    }
//    const templateStr = fs.readFileSync(path.resolve(__dirname, DOCS_TEMPLATE_DIR, 'layouts.md.handlebars')).toString('utf8')
//    const template = Handlebars.compile(templateStr)
//    const result = template(allData)
//    fs.writeFileSync(path.resolve(__dirname, DOCS_OUTPUT_DIR, 'layouts.md'), result)

  }
});
